# Shorter Prompts

In [1]:
# Famous Artists

import random
import numpy as np
import pandas as pd

In [2]:
prompts = [    "A plane flying in the sky",    "A plane taking off from a runway",    "A plane landing on a tarmac",    "A plane soaring through the clouds",    "A plane flying over the ocean",    "A plane cruising at high altitude",    "A plane banking in the air",    "A plane descending towards the ground",    "A plane approaching a landing strip",    "A plane taxiing on the runway",    "A plane parked at the gate",    "A plane waiting on the tarmac",    "A plane revving its engines",    "A plane preparing for takeoff",    "A plane ascending into the sky",    "A plane circling the airport",    "A plane passing overhead",    "A plane in mid-flight",    "A plane taking off into the sunset",    "A plane landing at night"]


artists = ['plane']*len(prompts)


prompts.extend([    "A ship sailing on the sea",    "A ship anchored in the harbor",    "A ship approaching the shore",    "A ship docking at the pier",    "A ship leaving the port",    "A ship cruising through the waves",    "A ship passing by in the distance",    "A ship with full sails",    "A ship moving slowly through the water",    "A ship with a cargo of containers",    "A ship carrying passengers",    "A ship with a crew on deck",    "A ship navigating through a storm",    "A ship in rough seas",    "A ship on a calm sea",    "A ship traveling across the ocean",    "A ship in the sunset",    "A ship in the moonlight",    "A ship in the fog",    "A ship in the mist"]
)
artists.extend(['ship']*20)

prompts.extend([    "A dog running in the park",    "A dog playing with a ball",    "A dog barking at a squirrel",    "A dog jumping over a hurdle",    "A dog digging in the dirt",    "A dog wagging its tail",    "A dog chasing its tail",    "A dog sitting patiently",    "A dog lying down in the sun",    "A dog walking on a leash",    "A dog drinking from a bowl",    "A dog panting after exercise",    "A dog howling at the moon",    "A dog scratching its ear",    "A dog sniffing the ground",    "A dog waiting for its owner",    "A dog playing with other dogs",    "A dog barking at a stranger",    "A dog napping in the shade",    "A dog dressed up in a costume"]
)
artists.extend(['dog']*20)


prompts.extend([    "A car driving on the road",    "A car parked in a lot",    "A car speeding down the highway",    "A car turning at an intersection",    "A car braking suddenly",    "A car honking its horn",    "A car idling at a red light",    "A car accelerating from a stop",    "A car passing another car",    "A car filling up at a gas station",    "A car with its headlights on",    "A car with tinted windows",    "A car with a sunroof open",    "A car with a roof rack",    "A car with a dent in the bumper",    "A car with a custom paint job",    "A car with a flat tire",    "A car with a busted taillight",    "A car with smoke coming out of the engine",    "A car driving in the rain"]
)
artists.extend(['car']*20)

prompts.extend([    "A bird flying in the sky",    "A bird perched on a branch",    "A bird building a nest",    "A bird singing a song",    "A bird soaring in the wind",    "A bird flapping its wings",    "A bird pecking at the ground",    "A bird with a worm in its beak",    "A bird with colorful feathers",    "A bird taking flight",    "A bird diving into the water",    "A bird in a birdhouse",    "A bird with a mate",    "A bird with a broken wing",    "A bird with a long beak",    "A bird with a short tail",    "A bird with a round body",    "A bird with a sharp talon",    "A bird with a distinctive call",    "A bird in a flock"]
)
artists.extend(['bird']*20)

In [3]:
seeds = [random.randint(0,5000) for i in prompts]
case_numbers = np.arange(len(seeds))

df = pd.DataFrame({'case_number': case_numbers, 'prompt': prompts, 'evaluation_seed': seeds, 'object': artists})
df

    case_number                              prompt  evaluation_seed object
0             0           A plane flying in the sky             2671  plane
1             1    A plane taking off from a runway             2275  plane
2             2         A plane landing on a tarmac              838  plane
3             3  A plane soaring through the clouds             2828  plane
4             4       A plane flying over the ocean              337  plane
..          ...                                 ...              ...    ...
95           95            A bird with a short tail             1119   bird
96           96            A bird with a round body             2889   bird
97           97           A bird with a sharp talon             1448   bird
98           98      A bird with a distinctive call             3747   bird
99           99                   A bird in a flock             3802   bird

[100 rows x 4 columns]

In [4]:
df.to_csv('object_prompts.csv')